In [9]:
#import the libraries

import numpy as np
import pandas as pd
import sklearn  #..we do the data preprocessing

In [11]:
# import the dataset

from google.colab import files
uploaded = files.upload()

Saving zomato_indore.csv to zomato_indore.csv


In [20]:
import io

data = pd.read_csv(io.BytesIO(uploaded['zomato_indore.csv']))
print(data)

      Unnamed: 0  ... rating_text
0              0  ...   Very Good
1              1  ...   Very Good
2              2  ...   Very Good
3              3  ...   Very Good
4              4  ...   Very Good
...          ...  ...         ...
2846        2953  ...   Very Good
2847        2954  ...   Very Good
2848        2955  ...   Very Good
2849        2956  ...   Very Good
2850        2957  ...   Very Good

[2851 rows x 10 columns]


In [21]:
type(data)

pandas.core.frame.DataFrame

In [22]:
data_new = data[['locality','latitude','longitude','cuisines','average_cost_for_two','aggregate_rating','votes']]

In [23]:
data_new.head()

locality   latitude  ...  aggregate_rating votes
0              Sudama Nagar  22.696331  ...               4.3   860
1  BCM Heights, Vijay Nagar  22.755705  ...               4.2   683
2         Sarwate Bus Stand  22.714090  ...               4.3  2030
3               Old Palasia  22.725712  ...               4.3  2987
4         Sarwate Bus Stand  22.714086  ...               4.3  3441

[5 rows x 7 columns]

In [24]:
#since our dependent column is in penultimate(2nd-last) position, we have to move it to one of the extreme position

temp = data_new.pop('aggregate_rating')
data_new.insert(len(data_new.columns),'rating_new', temp)

In [25]:
data_new.head()

locality   latitude  ...  votes rating_new
0              Sudama Nagar  22.696331  ...    860        4.3
1  BCM Heights, Vijay Nagar  22.755705  ...    683        4.2
2         Sarwate Bus Stand  22.714090  ...   2030        4.3
3               Old Palasia  22.725712  ...   2987        4.3
4         Sarwate Bus Stand  22.714086  ...   3441        4.3

[5 rows x 7 columns]

In [26]:
# Extraction of dependent and independent columns
# iloc is used to extract independent and dependent columns 
# x - independent columns
# y - dependent column

#In x we will consider only locality,latitude,longitude,cuisines,average_cost_for_two,votes

x = data_new.iloc[ : ,0:6].values
print(x)

[['Sudama Nagar' 22.69633146 75.83485689 'Fast Food' 500 860]
 ['BCM Heights, Vijay Nagar' 22.75570457 75.89528706
  'Cafe, Fast Food, Bakery' 500 683]
 ['Sarwate Bus Stand' 22.71408953 75.86885054 'North Indian' 350 2030]
 ...
 ['Radisson Blu Hotel, Vijay Nagar' 22.75003008 75.90347148
  'Asian, Chinese, Momos' 1850 248]
 ['Radisson Blu Hotel, Vijay Nagar' 22.75003534 75.90347953
  'North Indian, Kashmiri' 1850 200]
 ['Indore Marriott Hotel, Vijay Nagar' 22.7528774 75.88345349 'Bakery'
  1500 197]]


In [27]:
y = data_new.iloc[ : ,6:7].values # dependent variable
print(y)

[[4.3]
 [4.2]
 [4.3]
 ...
 [4.6]
 [4.3]
 [4.4]]


In [28]:
# to change x into dataframe, we use above command. In this way we can use head() or .null() on x as well.
# If x is changed into dataframe, then we need to add iloc while using fit_transform method

x = data_new.iloc[ : , 0:6]  
x.head()

locality   latitude  ...  average_cost_for_two votes
0              Sudama Nagar  22.696331  ...                   500   860
1  BCM Heights, Vijay Nagar  22.755705  ...                   500   683
2         Sarwate Bus Stand  22.714090  ...                   350  2030
3               Old Palasia  22.725712  ...                   800  2987
4         Sarwate Bus Stand  22.714086  ...                   350  3441

[5 rows x 6 columns]

In [29]:
y = data_new.iloc[ : , 6:7]  
y.head()

rating_new
0         4.3
1         4.2
2         4.3
3         4.3
4         4.3

In [30]:
# Checking data types

x.dtypes

locality                 object
latitude                float64
longitude               float64
cuisines                 object
average_cost_for_two      int64
votes                     int64
dtype: object

In [31]:
y.dtypes

rating_new    float64
dtype: object

In [32]:
# using dictionary to convert datatypes of specific columns

convert_dict = {'locality':str,'latitude':float,'longitude':float,'cuisines':str,'average_cost_for_two':int,'votes':int}
x = x.astype(convert_dict)
print(x.dtypes)   

y = y.astype(float)
print(y.dtypes)

locality                 object
latitude                float64
longitude               float64
cuisines                 object
average_cost_for_two      int64
votes                     int64
dtype: object
rating_new    float64
dtype: object


In [33]:
# There are many unique values and we have to turn it into numeric form for feature scalling. 
# Since OHE will return many columns which is not suitable, therefore we use label encoding.

# Handling categorical data using Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

x.iloc[ : ,0] = le.fit_transform(x.iloc[ : ,0])
x.iloc[ : ,1] = le.fit_transform(x.iloc[ : ,1])
x.iloc[ : ,2] = le.fit_transform(x.iloc[ : ,2])
x.iloc[ : ,3] = le.fit_transform(x.iloc[ : ,3])
x.iloc[ : ,4] = le.fit_transform(x.iloc[ : ,4])
x.iloc[ : ,5] = le.fit_transform(x.iloc[ : ,5])

x.head()

locality  latitude  longitude  cuisines  average_cost_for_two  votes
0        62       146         93        97                     9    367
1         4       815        692        42                     9    343
2        59       276        277       175                     6    394
3        45       518        536       233                    15    398
4        59       275        276       175                     6    399

In [34]:
# Handling categorical data using Label Encoding
y.iloc[ : ,0] = le.fit_transform(x.iloc[ : ,0])

y.head()

rating_new
0          62
1           4
2          59
3          45
4          59

In [35]:
#Splitting the dataset into training dataset and testing dataset

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state=100) 

#The order of the above variables on L.H.S should be exact.
#random_state is optional part.
#If random state is taken, it signifies that sequence of data is changed and any row can be taken as testing dataset's part.
#It can be any number and particular sequence is attached to particular number.

In [36]:
print(len(x_train))
print(len(x_train.columns))
print(len(x_test))
print(len(x_test.columns))
print(len(y_train))
print(len(y_train.columns))
print(len(y_test))
print(len(y_test.columns))

2280
6
571
6
2280
1
571
1


In [37]:
#Feature Scaling using Sandardization

from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x_train = st.fit_transform(x_train)
x_test = st.transform(x_test)

**Implementing Deep Learning Model:**

In [49]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([ 
    keras.layers.Dense(4, input_shape=(6, ), activation = "relu"),
    keras.layers.Dense(1, activation = "softmax")
])

In [50]:
model.compile( loss = 'categorical_crossentropy', optimizer = 'adam' , metrics=['accuracy'] )

In [53]:
model.fit(x_train, y_train, epochs = 10)

Epoch 1/10
72/72 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0377
Epoch 2/10
72/72 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0377
Epoch 3/10
72/72 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0377
Epoch 4/10
72/72 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0377
Epoch 5/10
72/72 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0377
Epoch 6/10
72/72 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0377
Epoch 7/10
72/72 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0377
Epoch 8/10
72/72 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0377
Epoch 9/10
72/72 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0377
Epoch 10/10
72/72 [==============================] - 0s 1ms/step - loss: 0.0000e+0

In [54]:
model.evaluate(x_test, y_test)

18/18 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0245


[0.0, 0.024518389254808426]

In [57]:
y_pred = model.predict(x_test)
y_pred

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [60]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)*100

2.4518388791593697

In [62]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
cm

array([[  0,   0,   0, ...,   0,   0,   0],
       [ 10,  14,   2, ...,   7, 106,  13],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]])

In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         1.0       1.00      0.02      0.05       571
         2.0       0.00      0.00      0.00         0
         3.0       0.00      0.00      0.00         0
         4.0       0.00      0.00      0.00         0
         5.0       0.00      0.00      0.00         0
         6.0       0.00      0.00      0.00         0
         7.0       0.00      0.00      0.00         0
         8.0       0.00      0.00      0.00         0
         9.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00         0
        12.0       0.00      0.00      0.00         0
        14.0       0.00      0.00      0.00         0
        15.0       0.00      0.00      0.00         0
        16.0       0.00      0.00      0.00         0
        17.0       0.00      0.00      0.00         0
        18.0       0.00      0.00      0.00         0
        19.0       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
